import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

function main() {
  const __filename = fileURLToPath(import.meta.url)
  const __dirname = path.dirname(__filename)
  const repoRoot = path.resolve(__dirname, '..')
  const pkgPath = path.join(repoRoot, 'package.json')
  if (!fs.existsSync(pkgPath)) {
    console.error('package.json not found')
    process.exit(1)
  }

  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'))
  const version = pkg.version || '0.0.0'

  const outPath = path.join(repoRoot, 'src', 'lib', 'app-version.ts')
  const content = `// Auto-generated by scripts/write-version.js
// Do not edit manually. This file is overwritten on build/dev.
export const APP_VERSION = '${version}'
`

  fs.writeFileSync(outPath, content, 'utf8')
  console.log(`Wrote APP_VERSION=${version} to ${path.relative(repoRoot, outPath)}`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main()
}
